name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: -3
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: raulsouzalima
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
